services:
  mysql:
    image: mysql:8.4
    container_name: digital-bookstore-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital-bookstore
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
